<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/iambeejayayo/image/upload/v1547954566/fav-500.png" alt="Mark Essien">
                        <h6>Monday Udowong</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="https://twitter.com/i_am_mundial" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/mundial419" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://mondaydev1.000webhostapp.com" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        I am a front-end web developer specialized in Javascript. I currently work as a freelancer and have an immense passion for writing. Favourite activity? I wasn’t planning on saying this, but yes, coding.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | HTML | CSS</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
